export const FETCH_SAMPLE_ARTISTS = 'FETCH_SAMPLE_ARTISTS';
export const FETCH_AGGREGATE_DATA = 'FETCH_AGGREGATE_DATA';
export const FETCH_ARTIST_ANALYSIS = 'FETCH_ARTIST_ANALYSIS';
export const FETCH_GENIUS_ARTISTS = 'FETCH_GENIUS_ARTISTS';
export const SELECT_GENRE = 'SELECT_GENRE';
export const LOAD_GENRE = 'LOAD_GENRE';
export const SELECT_ARTIST = 'SELECT_ARTIST';